spring:
  profiles:
    active: dev
    include : secret
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:h2:./nbe2_2_dev;MODE=MYSQL
    #    DB_CLOSE_ON_EXIT=FALSE # MySQL 모드 설정
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        hibernate.generate_statistics: true
        jdbc:
          batch_size: 1000
        order_inserts : true
        order_updates:  true
      show_sql: true

logging:
  level:
    com.example.kotlindevelop: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.transaction.interceptor: TRACE